### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by egorbarsukoff** [neg99/NE_DataAnalysis#5]
Похоже, что здесь ошибка в знаках (SST + SSE - SST). Причем эту опечатку видел не в одном конспекте помимо этого

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/28301369/82166961-e158ec00-98c2-11ea-9ece-9deda37e9736.png">

**Comment by neg99** [comment]
Спасибо, исправлено.
 
=========
